query getObjects($slug: String!) {
  getObjects(
    bucket_slug: "capacitor-template-nuxt-production"
    read_key: "Xyjlrefnietn7uAWOMWNCVNdAqiAV66PFKWR8pAacbTFW1ufgM"
    input: { query: { slug: $slug } }
  ) {
    objects {
      id
      title
      content
      slug
      metadata
    }
  }
}
